version: "3.8"

services:
  app:
    build: .
    environment:
      - ADMIN_TOKEN=bc6acdd7-9de0-495f-86ea-20beda48d626
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=chore-management
      - WAIT_FOR_IT_ADDRESS=database:3306
    ports:
      - "8080:8080"

  database:
    image: mysql:oracle
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chore-management
    ports:
      - "3306:3306"

  allure:
    image: frankescobar/allure-docker-service
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY=1
    volumes:
      - "./test/reports:/app/allure-results"
      - "./test/history:/app/default-reports"
    ports:
      - 5050:5050
