version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: delivery/Dockerfile
    container_name: app
    environment:
      - CREATE_DATABASE=true
      - ADMIN_API_KEY=bc6acdd7-9de0-495f-86ea-20beda48d626
      - APPLICATION_SECRET=whatever
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=chore-management
      - WAIT_FOR_IT_ADDRESS=database:3306
      - DATABASE_URL=mysql://root:root@database:3306/chore-management
    ports:
      - "8080:8080"
    healthcheck:
      interval: 3s
      timeout: 1s
      start_period: 5s
      retries: 0
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]

  database:
    image: mysql:oracle
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - "6379:6379"
