version: "3.8"

services:
  app:
    build: .
    container_name: app
    environment:
      - ADMIN_API_KEY=bc6acdd7-9de0-495f-86ea-20beda48d626
      - APPLICATION_SECRET=whatever
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=chore-management
      - WAIT_FOR_IT_ADDRESS=database:3306
      - DATABASE_URL=mysql://root:root@database:3306/chore-management
    ports:
      - "8080:8080"

  database:
    image: mysql:oracle
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chore-management
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - "6379:6379"
