version: "3.8"

services:
  app:
    build: .
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=chore-management
      - WAIT_FOR_IT_ADDRESS=database:3306
      # Export this environment variable if the host TZ is not UTC
      - TZ
    ports:
      - "8080:8080"

  database:
    image: mysql:oracle
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chore-management
    ports:
      - "3306:3306"
