"""Initial migration

Revision ID: 4f13bbeec380
Revises: 
Create Date: 2022-12-04 01:07:11.515090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f13bbeec380'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_type', sa.String(length=25), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('week_id', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chore_type',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rotations',
    sa.Column('week_id', sa.String(length=7), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('user_ids_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('week_id')
    )
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rotation_sign', sa.Enum('positive', 'negative', name='rotationsign'), nullable=False),
    sa.Column('assignment_order', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_type_id', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('tickets', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('chore_type_id', sa.String(length=25), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('user_id_from', sa.String(length=40), nullable=False),
    sa.Column('user_id_to', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('week_id', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('api_key', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transfer')
    op.drop_table('ticket')
    op.drop_table('settings')
    op.drop_table('rotations')
    op.drop_table('chore_type')
    op.drop_table('chore')
    # ### end Alembic commands ###
