"""Add rotations

Revision ID: 7a6fdba1ba11
Revises: 844dc2b45c36
Create Date: 2022-12-02 13:36:38.630340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6fdba1ba11'
down_revision = '844dc2b45c36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rotations',
    sa.Column('week_id', sa.String(length=7), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('user_ids_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('week_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rotations')
    # ### end Alembic commands ###
