"""Initial migration

Revision ID: 9a44996b3b90
Revises: 
Create Date: 2022-11-27 18:40:04.930326

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9a44996b3b90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_type', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('week_id', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choretype',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('rotation_sign', sa.Enum('positive', 'negative', name='rotationsign'), nullable=False),
    sa.Column('assignment_order', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_type_id', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('tickets', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('chore_type_id', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('user_id_from', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('user_id_to', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('week_id', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transfer')
    op.drop_table('ticket')
    op.drop_table('settings')
    op.drop_table('choretype')
    op.drop_table('chore')
    # ### end Alembic commands ###
