"""Initial migration

Revision ID: a548ce2f20a3
Revises: 
Create Date: 2022-11-26 18:38:11.228870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a548ce2f20a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore_types',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chore_type', sa.String(length=25), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('week_id', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('primary_key', sa.String(length=36), nullable=False),
    sa.Column('assignment_order', sa.String(length=2048), nullable=False),
    sa.Column('rotation_sign', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('primary_key')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_type_id', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('tickets', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('chore_type_id', sa.String(length=25), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('user_id_from', sa.String(length=40), nullable=False),
    sa.Column('user_id_to', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('week_id', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('transfers')
    op.drop_table('tickets')
    op.drop_table('settings')
    op.drop_table('chores')
    op.drop_table('chore_types')
    # ### end Alembic commands ###
