name: E2E tests

on:
  # TODO: delete line
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: "false"
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11

      - name: Launch docker-compose
        run: docker-compose up --build -d

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install
        run: poetry install

      - name: Run tests e2e
        run: utils/wait-for-it.sh 127.0.0.1:8080 -t 0 -- behave

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: "Test Reports"
          path: test/reports
