name: E2E tests

on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      POETRY_VIRTUALENVS_CREATE: "false"
      TERM: xterm-color
    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Fail if PR is in draft
        if: github.event.pull_request.draft
        run: exit 1

      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.3.2

      - name: poetry info
        run: poetry debug info && poetry env info

      - name: Run poetry install
        run: poetry install

      - name: Lint
        id: lint
        run: .github/scripts/lint.sh

      - name: Run tests e2e
        run: ./run-tests.sh

      - name: Adding summary
        run: echo "Defined $(ls -l test/reports/*.json | wc -l) scenarios" >> $GITHUB_STEP_SUMMARY

      - name: Compress test results
        if: |
          !contains(fromJson('["cancelled", "skipped"]'), steps.lint.conclusion)
        run: tar cvfz test/reports.zip test/reports

      - uses: actions/upload-artifact@v2
        if: |
          !contains(fromJson('["cancelled", "skipped"]'), steps.lint.conclusion)
        with:
          name: "Test Reports"
          path: test/reports.zip
