name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get project version
        id: project_version
        run: echo "::set-output name=version::$(cat pyproject.toml | grep version | head -1 | cut -d '=' -f2 | tr -d '"')"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: delivery/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: "sralloza/chore-management-api:${{ steps.project_version.outputs.version }}"
